name: kacha_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

#  authentication_repository:
#    path: packages/authentication_repository
#
#  form_inputs:
#    path: packages/form_inputs

  cupertino_icons: ^1.0.2
  velocity_x: ^4.1.0
  font_awesome_flutter: ^10.1.0
  image_picker: ^1.0.2
  intl: ^0.19.0
  searchfield: ^0.9.0
  carousel_slider: ^4.1.1
  badges: ^3.0.3
  url_launcher: ^6.1.6
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  flutter_bloc: ^8.1.1
  formz: ^0.6.0
  firebase_core: ^2.21.0
  firebase_auth: ^4.1.4
  firebase_storage: ^11.0.6
  firebase_analytics: ^10.0.6
  http: ^1.1.2
  uuid: ^4.3.3
  location: ^5.0.2+1
  autocomplete_textfield: ^2.0.1
  pinput: ^3.0.0
  inspection: ^0.0.13
  basic_utils: ^5.4.0
  path_provider: ^2.0.14
  jwt_decoder: ^2.0.1
  image: ^4.1.4
  flutter_native_splash: ^2.0.0
  firebase_messaging: ^14.6.2
  package_info_plus: ^5.0.1
  firebase_app_check: ^0.2.0
  cached_network_image: ^3.2.3

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
