name: kacha_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  authentication_repository:
    path: packages/authentication_repository

  form_inputs:
    path: packages/form_inputs

  equatable: ^2.0.3
  firebase_core: ^2.23.0
  flow_builder: ^0.0.9
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.1.0
  formz: ^0.6.0
  google_fonts: ^4.0.0
  meta: ^1.7.0
  url_launcher: ^6.1.6

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
