name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cache:
    path: ../cache
  equatable: ^2.0.5
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  google_sign_in: ^6.1.0
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  firebase_auth_platform_interface: ^7.0.5
  firebase_core_platform_interface: ^5.0.0
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.7
